@extends('master')

@section('title', 'AI Analysis Details')

@section('content')
@php
    $analysisData = is_array($analysis->analysis_data) ? $analysis->analysis_data : json_decode($analysis->analysis_data, true);
    $patient = $analysis->appointment ? $analysis->appointment->patient : null;
@endphp

<div class="dashboard-container">
    <div class="container-fluid">
        <!-- Header Section -->
        <div class="row mb-4">
            <div class="col-12">
                <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center mb-4">
                    <!-- Back Button & Title -->
                    <div class="d-flex align-items-center mb-3 mb-md-0">
                        <a href="javascript:history.back()" class="btn btn-secondary-custom me-3">
                            <i class="fas fa-arrow-left me-2"></i>Back
                        </a>
                        <div>
                            <h1 class="h2 mb-1 fw-bold">AI Analysis Details</h1>
                            <small class="text-muted">Analysis ID: #{{ $analysis->id }}</small>
                        </div>
                    </div>

                    <!-- Status Badge -->
                    @php
                        $statusClasses = [
                            'active' => 'bg-success text-white',
                            'reviewed' => 'bg-primary text-white',
                            'archived' => 'bg-secondary text-white'
                        ];
                        $statusClass = $statusClasses[$analysis->status] ?? 'bg-secondary text-white';
                    @endphp
                    <span class="badge {{ $statusClass }} px-3 py-2 rounded-pill fs-6">
                        <i class="fas fa-brain me-2"></i>
                        {{ ucfirst($analysis->status) }}
                    </span>
                </div>
            </div>
        </div>

        <!-- Analysis Overview Card -->
        <div class="card shadow-sm mb-4">
            <div class="card-header bg-primary text-white">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h3 class="card-title mb-1 fw-bold">
                            <i class="fas fa-brain me-2"></i>AI Medical Copilot Analysis
                        </h3>
                        <p class="mb-0 opacity-75">Generated on {{ $analysis->generated_at->format('M j, Y \a\t g:i A') }}</p>
                    </div>
                    @if($analysis->appointment)
                        <a href="{{ route('appointments.show', $analysis->appointment) }}" class="btn btn-outline-light btn-sm">
                            <i class="fas fa-calendar me-1"></i>View Appointment
                        </a>
                    @endif
                </div>
            </div>

            <div class="card-body">
                <div class="row">
                    <div class="col-md-6 mb-3 mb-md-0">
                        <div class="d-flex align-items-center">
                            <div class="bg-primary bg-opacity-10 rounded-3 p-3 me-3">
                                <i class="fas fa-user-md text-primary fs-4"></i>
                            </div>
                            <div>
                                <h6 class="fw-semibold mb-1">Generated By</h6>
                                <p class="text-muted mb-0">{{ $analysis->doctor ? $analysis->doctor->name : 'Unknown Doctor' }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="d-flex align-items-center">
                            <div class="bg-success bg-opacity-10 rounded-3 p-3 me-3">
                                <i class="fas fa-user text-success fs-4"></i>
                            </div>
                            <div>
                                <h6 class="fw-semibold mb-1">Patient</h6>
                                <p class="text-muted mb-0">
                                    @if($patient)
                                        {{ $patient->name }}
                                        @if($patient->date_of_birth)
                                            ({{ $patient->date_of_birth->age }} years old)
                                        @endif
                                    @else
                                        Unknown Patient
                                    @endif
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                @if($analysis->appointment)
                    <hr class="my-3">
                    <div class="row">
                        <div class="col-md-6">
                            <h6 class="fw-semibold mb-2">Appointment Details</h6>
                            <p class="mb-1"><strong>Date:</strong> {{ $analysis->appointment->appointment_date->format('M j, Y \a\t g:i A') }}</p>
                            <p class="mb-1"><strong>Reason:</strong> {{ $analysis->appointment->reason }}</p>
                            @if($analysis->appointment->symptoms)
                                <p class="mb-0"><strong>Symptoms:</strong> {{ $analysis->appointment->symptoms }}</p>
                            @endif
                        </div>
                        <div class="col-md-6">
                            <h6 class="fw-semibold mb-2">Status</h6>
                            <p class="mb-1"><strong>Analysis Status:</strong>
                                <span class="badge bg-{{ $analysis->status === 'reviewed' ? 'success' : ($analysis->status === 'active' ? 'warning' : 'secondary') }}">
                                    {{ ucfirst($analysis->status) }}
                                </span>
                            </p>
                            @if($analysis->reviewed_at)
                                <p class="mb-0"><strong>Reviewed:</strong> {{ $analysis->reviewed_at->format('M j, Y \a\t g:i A') }}</p>
                                @if($analysis->reviewer)
                                    <p class="mb-0"><strong>Reviewed by:</strong> {{ $analysis->reviewer->name }}</p>
                                @endif
                            @endif
                        </div>
                    </div>
                @endif
            </div>
        </div>

        <!-- Analysis Content -->
        <div class="row">
            <div class="col-12">
                <!-- Medical Case Summary -->
                @if(isset($analysisData['medical_case_summary']) && !empty($analysisData['medical_case_summary']))
                    <div class="card shadow-sm mb-4">
                        <div class="card-header bg-primary text-white">
                            <h5 class="card-title mb-0 fw-bold">
                                <i class="fas fa-file-medical me-2"></i>Medical Case Summary
                            </h5>
                        </div>
                        <div class="card-body">
                            <div class="bg-light rounded-3 p-4">
                                <p class="mb-0 fs-5">{{ $analysisData['medical_case_summary'] }}</p>
                            </div>
                        </div>
                    </div>
                @endif

                <div class="row">
                    <!-- Differential Considerations -->
                    <div class="col-lg-6 mb-4">
                        @if(isset($analysisData['differential_considerations']) && !empty($analysisData['differential_considerations']))
                            <div class="card shadow-sm h-100">
                                <div class="card-header bg-warning" style="color: var(--navy);">
                                    <h5 class="card-title mb-0 fw-bold">
                                        <i class="fas fa-list-check me-2"></i>Differential Considerations
                                    </h5>
                                </div>
                                <div class="card-body">
                                    <div class="bg-warning bg-opacity-10 rounded-3 p-3">
                                        <p class="text-muted small mb-3"><em>These are suggestions, not diagnoses. Physician judgment required.</em></p>
                                        <ul class="list-unstyled mb-0">
                                            @foreach($analysisData['differential_considerations'] as $consideration)
                                                @if(is_array($consideration) && isset($consideration['consideration']))
                                                    <li class="mb-3">
                                                        <strong>{{ $consideration['consideration'] }}</strong>
                                                        @if(isset($consideration['rationale']))
                                                            <br><small class="text-muted">{{ $consideration['rationale'] }}</small>
                                                        @endif
                                                    </li>
                                                @else
                                                    <li class="mb-2">{{ $consideration }}</li>
                                                @endif
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        @endif
                    </div>

                    <!-- Red Flags -->
                    <div class="col-lg-6 mb-4">
                        @if(isset($analysisData['red_flags']) && !empty($analysisData['red_flags']))
                            <div class="card shadow-sm h-100">
                                <div class="card-header bg-danger text-white">
                                    <h5 class="card-title mb-0 fw-bold">
                                        <i class="fas fa-flag me-2"></i>Red Flags
                                    </h5>
                                </div>
                                <div class="card-body">
                                    <div class="bg-danger bg-opacity-10 rounded-3 p-3">
                                        <p class="text-muted small mb-3"><em>Consider urgent evaluation if clinically indicated.</em></p>
                                        <ul class="list-unstyled mb-0">
                                            @foreach($analysisData['red_flags'] as $flag)
                                                <li class="mb-2 text-danger">
                                                    <i class="fas fa-exclamation-triangle me-2"></i>{{ $flag }}
                                                </li>
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        @else
                            <div class="card shadow-sm h-100">
                                <div class="card-header bg-success text-white">
                                    <h5 class="card-title mb-0 fw-bold">
                                        <i class="fas fa-check-circle me-2"></i>Red Flags
                                    </h5>
                                </div>
                                <div class="card-body">
                                    <div class="bg-success bg-opacity-10 rounded-3 p-3 text-center">
                                        <i class="fas fa-check-circle text-success fs-1 mb-2"></i>
                                        <p class="mb-0 text-success fw-semibold">No immediate red flags detected</p>
                                        <small class="text-muted">Based on available data</small>
                                    </div>
                                </div>
                            </div>
                        @endif
                    </div>
                </div>

                <!-- Follow-up Questions -->
                @if(isset($analysisData['follow_up_questions']) && !empty($analysisData['follow_up_questions']))
                    <div class="card shadow-sm mb-4">
                        <div class="card-header bg-info text-white">
                            <h5 class="card-title mb-0 fw-bold">
                                <i class="fas fa-question-circle me-2"></i>Follow-up Questions
                            </h5>
                        </div>
                        <div class="card-body">
                            <div class="bg-info bg-opacity-10 rounded-3 p-3">
                                <p class="text-muted small mb-3"><em>Questions to help complete the clinical picture and reduce oversight.</em></p>
                                <ul class="list-unstyled mb-0">
                                    @foreach($analysisData['follow_up_questions'] as $question)
                                        <li class="mb-2">
                                            <i class="fas fa-question-circle text-info me-2"></i>{{ $question }}
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                @endif

                <!-- Patient History -->
                @if(isset($analysisData['patient_history']) && !empty($analysisData['patient_history']))
                    <div class="card shadow-sm mb-4">
                        <div class="card-header bg-secondary text-white">
                            <h5 class="card-title mb-0 fw-bold">
                                <i class="fas fa-history me-2"></i>Patient History Considered
                            </h5>
                        </div>
                        <div class="card-body">
                            @php $history = $analysisData['patient_history']; @endphp

                            @if(isset($history['chronic_conditions']) && !empty($history['chronic_conditions']))
                                <div class="mb-3">
                                    <h6 class="fw-semibold text-primary"><i class="fas fa-heartbeat me-1"></i>Chronic Conditions:</h6>
                                    <ul class="list-inline">
                                        @foreach($history['chronic_conditions'] as $condition)
                                            <li class="list-inline-item">
                                                <span class="badge bg-primary">{{ $condition }}</span>
                                            </li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            @if(isset($history['previous_diagnoses']) && !empty($history['previous_diagnoses']))
                                <div class="mb-3">
                                    <h6 class="fw-semibold text-primary"><i class="fas fa-stethoscope me-1"></i>Previous Diagnoses:</h6>
                                    <ul class="list-unstyled">
                                        @foreach($history['previous_diagnoses'] as $diagnosis)
                                            <li class="mb-1">{{ $diagnosis }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            @if(isset($history['previous_ai_analyses']) && !empty($history['previous_ai_analyses']))
                                <div class="mb-3">
                                    <h6 class="fw-semibold text-primary"><i class="fas fa-brain me-1"></i>Previous AI Analyses:</h6>
                                    @foreach($history['previous_ai_analyses'] as $prevAnalysis)
                                        <div class="border-start border-info border-3 ps-3 mb-3 bg-light rounded">
                                            <small class="text-muted">{{ $prevAnalysis['generated_at'] ?? 'Unknown date' }}</small>
                                            <p class="mb-1">{{ $prevAnalysis['summary'] ?? 'No summary' }}</p>
                                            @if(isset($prevAnalysis['red_flags']) && !empty($prevAnalysis['red_flags']))
                                                <small class="text-danger">⚠️ Red flags: {{ implode(', ', $prevAnalysis['red_flags']) }}</small>
                                            @else
                                                <small class="text-success">✅ No red flags</small>
                                            @endif
                                        </div>
                                    @endforeach
                                </div>
                            @endif
                        </div>
                    </div>
                @endif

                <!-- Doctor Review -->
                @if($analysis->reviewed_at && $analysis->reviewer)
                    <div class="card shadow-sm mb-4">
                        <div class="card-header bg-success text-white">
                            <h5 class="card-title mb-0 fw-bold">
                                <i class="fas fa-user-md me-2"></i>Physician Review
                            </h5>
                        </div>
                        <div class="card-body">
                            <div class="bg-success bg-opacity-10 rounded-3 p-3">
                                <div class="mb-2">
                                    <strong>Reviewed by:</strong> {{ $analysis->reviewer ? $analysis->reviewer->name : 'Unknown Doctor' }}
                                    <small class="text-muted">on {{ $analysis->reviewed_at->format('M j, Y \a\t g:i A') }}</small>
                                </div>
                                @if($analysis->doctor_notes)
                                    <div>
                                        <strong>Notes:</strong>
                                        <p class="mb-0 mt-2">{{ $analysis->doctor_notes }}</p>
                                    </div>
                                @else
                                    <div>
                                        <em class="text-muted">No additional notes provided.</em>
                                    </div>
                                @endif
                            </div>
                        </div>
                    </div>
                @endif

                <!-- Compliance Information -->
                <div class="card shadow-sm">
                    <div class="card-body">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <div class="d-flex align-items-center">
                                    <div class="bg-primary bg-opacity-10 rounded-3 p-2 me-3">
                                        <i class="fas fa-shield-alt text-primary"></i>
                                    </div>
                                    <div>
                                        <h6 class="fw-semibold mb-1">Compliance Information</h6>
                                        <p class="text-muted small mb-0">
                                            This analysis was generated by AI Medical Copilot for clinical decision support only.
                                            All medical decisions must be made by qualified healthcare professionals.
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4 text-end">
                                <small class="text-muted">
                                    Generated: {{ $analysis->generated_at->format('M j, Y g:i A') }}<br>
                                    Version: AI-copilot-clinical-v1.1
                                </small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection